---
---


Research Statement
Up to the mid-1990’s, the US contained approximately 4,000 power plants. By the end of 2018, there will be approximately 1.2 million power plants, most of which will be residential rooftop solar and other renewable energy sources. This transition from concentrated, regulated fossil fuels to distributed, intermittent renewables has wide-reaching impacts on the reliability, cost, and environmental profile of the US electrical grid. These impacts and the policy options to address them are the focus of my research plan, with a particular eye toward the effects of energy storage.

Grid Transition
My job market paper (most recent version here) estimates the effect of energy storage on wholesale electricity prices in California, finding that storage decreases peak prices by up to 2.2% at the location of installation. Using a novel machine-learning method first applied in the Research and Development literature to find unobserved network linkages, I find substantial price effects from energy storage between nodes as well and find that a significant portion of these effects come from mitigating spikes associated with the “intermittency cost” of solar and wind.

While this economically meaningful effect is relevant to policy-makers, it does not tell the full story. In some “congested” parts of the grid, local electricity generators may leverage market power, charging high prices for electricity on days when transmission lines are at capacity and there is little accessible competition. Storage, when located in these areas, reduces market power, decreasing monopoly prices and generating a welfare improvement for customers. My preliminary research in “Locational Market Power: The Effect of Battery Storage in California” (prospective work-in-progress) finds the behavior of generators at nodes co-located with storage that is consistent with the exercise of market power. This prospective project draws on the Industrial Organization literature to estimate generator markup and assess the magnitude of welfare improvement from the elimination of market power by energy storage. Results will improve estimates of the public welfare implications of energy storage, and provide insight into the exercise of locational market power.

In tandem with my focus on energy infrastructure, I turn the lens to the environmental effects of energy storage operation. As storage alters the generators “dispatched” by a grid operator, it also alters the amount and distribution of pollutants such as Sulfur Dioxide, Carbon Dioxide, and more. This change in environmental externalities is important in understanding the welfare effects of energy storage. In a work-in-progress, “Environmental Impacts of Energy Storage,” I study this change by using the “marginal responding plant” literature, which estimates the hour-to-hour relationship between individual generators and a marginal change in electricity demanded or, in this case, displaced by storage. These changes in plant-level generation are then “dollarized” by summing up mortality and other impacts in an integrated assessment model. Estimates of the net effect of charging and discharging a battery will further improve estimates of the public welfare implications of energy storage, and answer an ongoing policy and regulatory debate on the carbon pollution effects of energy storage.

In a similar fashion, I seek to uncover the environmental dimensions of offshore vs. onshore wind. While a naïve perspective would assume that both generate the same electricity, this ignores the timing of generation, which is important as the “marginal responding plant,” the plant which would be displaced by additional wind generation, may change hour-to-hour and month-to-month. Since offshore wind is characterized by more consistent windspeed, offshore and onshore wind may displace different generators. If the timing tends to be such that one displaces a “dirtier” generator, then these environmental externalities must be considered when comparing wind sites; currently, they are not. This prospective project, “Out to Sea: The Environmental Dimensions of Offshore Wind,” will examine the expected reductions in pollution from offshore and onshore wind in order to help inform policymakers of the trade-offs inherent in site choice.

In a related working paper, “Heterogeneous Environmental and Grid Benefits from Rooftop Solar and the Costs of Inefficient Siting Decisions,” with Steve Sexton, Nicholas Muller, and Bobby Harris, we use the “marginal responding plant” model to estimate the hourly emission response to an increase in solar generation and, combined with modeled solar generation and an integrated assessment model of air pollution damages, we calculate the spatially-explicit value of solar generation, inclusive of the value of the environmental externalities. In this research, we find that a complete reallocation of solar panels between states could increase welfare by more than $1 billion and that few states are successful at capturing the air quality benefits generated by in-state solar incentives, suggesting a role for federal solutions or interstate Coasean bargaining.

Distributed Renewables
Another strand of my research focuses on household decisions on the installation of distributed generation (i.e. residential rooftop solar). This work elucidates the factors and influences that drive household adoption, which is a vital part of understanding the grid transition. Both pecuniary and non-pecuniary incentives are part of my research. For instance, in a published work “Promoting clean energy investment: An empirical analysis of property assessed clean energy” (Journal of Environmental Economics and Management 2014), I examined the effect of a novel form of solar financing known as Property Assessed Clean Energy (PACE) and found a sizable increase in solar uptake despite offering no pecuniary incentive. In current research with Bryan Bollinger, Ken Gillingham, and Steve Sexton titled “Peer Effects and Conspicuous Conservation in Rooftop Solar Adoptions,” I use LiDAR satellite imagery to assess the visibility of residential rooftop solar and estimate the effect that visible panels have on other homeowners’ installation decisions. These papers help to understand the non-pecuniary drivers of household solar uptake.

Price-based subsidies are an important part of my research as well. Understanding these effects requires more structural estimation methods. In another work-in-progress with Bryan Bollinger, Ken Gillingham, and Steve Sexton, “Valuing Solar Subsidies,” we leverage a proprietary Google Sunroof dataset on household-level rooftop generation potential combined with a dynamic discrete choice model to uncover the differential effect of up-front subsidies vs. “net metering” subsidies in driving household solar adoption. A reduced-form working paper version, “Household Discount Rates and Net Energy Metering Incentives for Rooftop Solar Adoption,” (available on request) examined zip-code level installation rates and leveraged discontinuities at utility and climate-zone boundaries to find that households discounted the flow of benefits from utility net metering – letting a solar panel’s net generation be deducted off of a home’s total bill – far greater than all widely used social discount rates. This suggests that up-front incentives are more effective at a lower cost to the government.

Energy efficiency plays an important part in the grid transition as well. In a related work-in-progress “Energy Insecurity and Redlined America,” I study the oft-noted phenomenon that low-income households frequently face excessive energy bills, despite their income limitations, that initially seem counter-intuitive. Some of this insecurity is attributable to the housing stock, which is less energy efficient in low income and minority neighborhoods. I link this phenomenon to historic housing discrimination policy known as “redlining” which, in the 1930’s, designated tracts of urban areas as “minority appropriate” and subsequently limited lending to whites only outside of those areas. I control for endogenous selection of “redlined” areas by leveraging variation in the original “redlining” survey data to identify redlined areas that originally had characteristics identical to nearby non-redlined areas, forming a quasi-experiment. Conditional on minority presence and income in both 1932 and 2010, current “redlined” areas have lower-efficiency housing stock and lower mobility of residents – a “hysteresis” effect from historic discrimination.

Beyond these concrete projects, many of which exist already as working papers or works-in-progress, I find that our understanding of the intermittency costs of renewables is limited and that there are myriad areas of exploration. Local congestion relief provided by distributed renewables are frequently cited by rooftop solar proponents, but little has been done to fully understand the range of economic effects on the grid. As utilities implement smart meters, allowing for time-of-use pricing and other means of bringing instantaneous marginal cost into household energy decisions, and as households have more and more options for demand shifting (e.g. electric vehicles as energy storage), it becomes vital to incorporate consumer decision into studies of grid operation. My research sits at the crossroads of these two effects, opening a broad array of subsequent policy-relevant research areas to explore.

Beyond Energy
While my focus is on energy, my research interests extend to the environment as well. Fracking, in particular, creates environmental externalities that must be accounted for in any economic analysis. To better understand the economic impact of fracking, I use household-level data on bottled water consumption in Ohio and Pennsylvania to estimate consumer demand functions for bottled water, accounting for the presence of fracking within a zip code. These demand functions, estimated with a random-parameters mixed logit, allow me to generate lower bounds on household change in willingness to pay to avoid consuming tap water in the presence of fracking. The results calculate a disamenity value of over $16 per household per year and are robust to multiple specifications. This working paper, “Averting expenditures and desirable goods: Consumer demand for bottled water in the presence of fracking” (available here) will be in submission shortly, targeting a top general applied economics journal.

My unique background in fisheries and energy allow me to collaborate on economic projects across both fields. Currently, I have one potential project examining regulatory aspects of the fisheries. In this project, I propose examining the potentially conflicting effects between social “sustainability ratings” on US-caught fish, and NMFS fishery management techniques. Data shows that dramatic reductions in cod quota in New England led to decreases in the price per pound of landings. Coincident with the quota cuts, many seafood sustainability groups rated Atlantic Cod as “red” or “do not buy.” This proposed research studies how these effects may interact in counter-intuitive ways. By lowering the scarcity value of the small amount of Atlantic Cod fishermen were permitted to land, seafood sustainability efforts may have decreased overall welfare while failing to reduce environmental externalities. I primarily maintain my fishery economics research as a potential means of collaboration within a future academic department.

Overall, my comprehensive interdisciplinary research plan builds on my previously published research and explores issues associated with renewable energy and the US grid while leaving space for extensions into environmental and IO-centered research. In sum total, successfully executing this targeted agenda will provide a valuable understanding of the economic processes that influence the grid transition, and will help guide policymakers by understanding current, and future, costs.