---
title: "Justin Kirkpatrick: Research"
---

<br>

# {.tabset .tabset-fade}

## Published

<br>

### Peer-reviewed Publications

<br>


#### __Distributional Consequences of Policies for Electric Heat Conversion__
Soren Anderson and A. Justin Kirkpatrick __Journal of the Assoc. of Environmental and Resource Economists (November 2024)__

Abstract: We study the adoption of air-source heat pumps for home heating. We estimate that 6%-8% ofalready-built homes converted to heat pumps during 2009-2020, while 25% of the new homes built during this period chose heat pumps. New adoptions concentrate among rural households in the South and West. Conversions are more diffuse, covering both urban and rural households in every region, and displacing whichever fuels are most prevalent in these places. Conversions and new adoptions are both sensitive to energy prices, accelerating when electricity prices fall or when natural gas, heating oil, or propane prices rise. In addition, we calculate the annual energy-cost savings from switching to a heat pump for a prototypical home in every U.S. census tract, based on local conditions, including current heating fuels, climate, and energy prices. We find massive variation, with low-income households in the Northeast and upper Midwest benefiting the most

Available [here.](https://www.journals.uchicago.edu/doi/full/10.1086/731147)

Ungated version [here.](Papers/AndersonKirkpatrick_heatpumps.pdf)

<br>

#### [__Visibility and Peer Influence in Durable Good Adoption__](https://pubsonline.informs.org/doi/abs/10.1287/mksc.2021.1306)

Bryan Bollinger, Ken Gillingham, A. Justin Kirkpatrick, Steven Sexton. __Marketing Science (June 2022)__

Abstract: The underlying mechanisms of peer influence in durable good adoption can lead to substantial heterogeneity in peer effects and the capacity of marketers to leverage them. In this paper, we exploit the plausibly exogenous orientation of solar panels sited to maximize power generation to determine whether geographically proximate peers' solar installations increase a household's probability of solar adoption more if they are visible from public roadways. We also examine heterogeneity in the effect of peer panel visibility due to the economic value of solar installations and the political orientations of potential adopters. Highly visible and proximal peer solar installations are shown to double the adoption probability relative to non-visible proximal installations. The effect of peer installation visibility is larger for households headed by voters registered as independents or Democrats, who are only influenced by the visible installations of their non-Republican peers.

Available [here.](https://pubsonline.informs.org/doi/abs/10.1287/mksc.2021.1306)

Earlier ungated version [here.](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3409420)



<br>

#### [__Heterogeneous Solar Capacity Benefits, Appropriability, and the Costs of Suboptimal Siting__](https://www.journals.uchicago.edu/doi/10.1086/714970)

Sexton, Steven E., A. Justin Kirkpatrick, Robert Harris, Nicholas Muller. __Journal of the Assoc. of Environmental and Resource Economists (September 2021)__

Formerly titled “Siting Solar PV Capacity to Maximize Environmental Benefits”

Abstract: Federal and state policies in the U.S. subsidize electricity generation from 1.4 million rooftop solar arrays because of pollution avoidance benefits and grid congestion relief. Yet because these benefits vary across the U.S. according to solar irradiance, technologies of electricity generators, and grid characteristics, the value of these benefits, and, consequently, the optimal subsidy, are largely unknown. Policy, therefore, is unlikely to have induced efficient solar investments. This paper (1) provides the first systematic, theoretically consistent, and empirically valid estimates of pollution damages avoidable by solar capacity in each U.S. zip code, (2) relates these external benefits to subsidy levels in each U.S. state, and (3) estimates the share of these benefits that spillover to other states. It also measures the energy value of capacity across the U.S. and the value of transmission congestion relief in California. Environmental benefits are shown to vary considerably across the U.S., and to largely spillover to neighboring states. Subsidy levels are essentially uncorrelated with environmental benefits contributing to installed capacity that sacrifices approximately $1 billion per year in environmental benefits. Energy value is estimated to vary less than environmental benefits, while California rooftop solar is shown to generate no congestion relief.

Available [here](https://www.journals.uchicago.edu/doi/10.1086/714970)

Download [NBER working paper (2018) here.](Papers/kirkpatrickSolar_Siting_wp.pdf)


 
<br>

#### [__Investing in local capacity to respond to a federal environmental mandate: Forest & economic impacts of the Green Municipality Program in the Brazilian Amazon__](https://www.sciencedirect.com/science/article/abs/pii/S0305750X20300176?via%3Dihub)

Sills, Erin, Alexander Pfaff, Luiza Andrade, A. Justin Kirkpatrick, and Rebecca Dickson. __World Development (2020)__

Abstract: For the past decade, the Brazilian federal government has offered a strong collective incentive for municipalities in the Amazon to reduce deforestation through its policy of ‘blacklisting’ municipalities where the most deforestation is occurring. We evaluate a state program to improve the capacity of local governments to respond to this incentive. The Green Municipality Program, or Programa Municípios Verdes (PMV), is voluntary: municipal governments in the state of Pará choose whether to participate in the program. To control for any differences in outcomes due solely to which municipal governments chose to participate, we employ two quasi-experimental methods: two-way fixed effects regression within a matched sample of municipalities; and the synthetic control method that compares each municipality to a synthetic match that followed a similar outcome trajectory prior to the program. We hypothesize that the PMV helped municipalities ameliorate the costs of complying with federal deforestation mandates, and we find that participation in the program increased total value added in blacklisted municipalities, with substantial heterogeneity as revealed through the synthetic control method. We show that this effect is not likely due to intensification in the agricultural sector, and we identify other possible mechanisms that would require additional data to test. By reducing the local costs of controlling deforestation, the PMV could make forest conservation more socially and politically sustainable in the long run.

Download [here.](https://www.sciencedirect.com/science/article/abs/pii/S0305750X20300176?via%3Dihub)



<br>

#### [__Seafood Prices Reveal Impacts of a Major Ecological Disturbance__](http://www.pnas.org/content/pnas/early/2017/01/24/1617948114.full.pdf)

Martin D. Smith, Atle Oglend, A. Justin Kirkpatrick, Frank Asche, Lori S. Bennear, J. Craig, James Nance. __Proceedings of the National Academy of Sciences (2017)__

Abstract: Coastal hypoxia (dissolved oxygen ≤ 2 mg/L) is a growing problem worldwide that threatens marine ecosystem services, but little is known about economic effects on fisheries. Here, we provide evidence that hypoxia causes economic impacts on a major fishery. Ecological studies of hypoxia and marine fauna suggest multiple mechanisms through which hypoxia can skew a population’s size distribution toward smaller individuals. These mechanisms produce sharp predictions about changes in seafood markets. Hypoxia is hypothesized to decrease the quantity of large shrimp relative to small shrimp and increase the price of large shrimp relative to small shrimp. We test these hypotheses using time series of size-based prices. Naive quantity-based models using treatment/control comparisons in hypoxic and non-hypoxic areas produce null results, but we find strong evidence of the hypothesized effects in the relative prices: Hypoxia increases the relative price of large shrimp compared with small shrimp. The effects of fuel prices provide supporting evidence. Empirical models of fishing effort and bioeconomic simulations explain why quantifying effects of hypoxia on fisheries using quantity data has been inconclusive. Specifically, spatial-dynamic feedbacks across the natural system (the fish stock) and human system (the mobile fishing fleet) confound “treated” and “control” areas. Consequently, analyses of price data, which rely on a market counterfactual, are able to reveal effects of the ecological disturbance that are obscured in quantity data. Our results are an important step toward quantifying the economic value of reduced upstream nutrient loading in the Mississippi Basin and are broadly applicable to other coupled human-natural systems.

Download [here.](http://www.pnas.org/content/pnas/early/2017/01/24/1617948114.full.pdf)

This paper was awarded the AAEA “Quality of Research Discovery” Award for 2018.

 
<br>

#### [__Estimating the Impacts of Local Policy Innovation: The Synthetic Control Method Applied to Tropical Deforestation__](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132590)

Sills, Erin O., Diego Herrera, A. Justin Kirkpatrick, Amintas Brandão Jr, Rebecca Dickson, Simon Hall, Subhrendu Pattanayak et al. __PLoS One (2015)__

Abstract: Quasi-experimental methods increasingly are used to evaluate the impacts of conservation interventions by generating credible estimates of counterfactual baselines. These methods generally require large samples for statistical comparisons, presenting a challenge for evaluating innovative policies implemented within a few pioneering jurisdictions. Single jurisdictions often are studied using comparative methods, which rely on analysts’ selection of best case comparisons. The synthetic control method (SCM) offers one systematic and transparent way to select cases for comparison, from a sizeable pool, by focusing upon similarity in outcomes before the intervention. We explain SCM, then apply it to one local initiative to limit deforestation in the Brazilian Amazon. The municipality of Paragominas launched a multi-pronged local initiative in 2008 to maintain low deforestation while restoring economic production. This was a response to having been placed, due to high deforestation, on a federal “blacklist” that increased enforcement of forest regulations and restricted access to credit and output markets. The local initiative included mapping and monitoring of rural land plus promotion of economic alternatives compatible with low deforestation. The key motivation for the program may have been to reduce the costs of blacklisting. However its stated purpose was to limit deforestation, and thus we apply SCM to estimate what deforestation would have been in a (counterfactual) scenario of no local initiative. We obtain a plausible estimate, in that deforestation patterns before the intervention were similar in Paragominas and the synthetic control, which suggests that after several years, the initiative did lower deforestation (significantly below the synthetic control in 2012). This demonstrates that SCM can yield helpful land-use counterfactuals for single units, with opportunities to integrate local and expert knowledge and to test innovations and permutations on policies that are implemented in just a few locations.

Download [here.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132590)


<br>

#### [__Promoting Clean Energy Investment: An Empirical Analysis of Property Assessed Clean Energy__](https://www.sciencedirect.com/science/article/pii/S0095069614000370)

Kirkpatrick, A. Justin, and Lori S. Bennear. __Journal of Environmental Economics and Management (2014)__

Abstract: From 2008 to 2010 a handful of Property-Assessed Clean Energy (PACE) programs offered property-secured loans to homeowners for residential clean energy investments. This analysis uses difference-in-differences models and synthetic counterfactual models to estimate the effect of three California PACE programs on residential photovoltaic installations. We find that PACE financing increases solar installations by approximately 3.8 watts per owner-occupied household per quarter, a 108\% increase over the mean watts per owner-occupied household. Because PACE financing carries equal or higher interest rates relative to alternative financing mechanism, we argue that PACE programs can address market barriers and help address the clean energy investment gap.

Download [here.](https://www.sciencedirect.com/science/article/pii/S0095069614000370)

This paper was featured in [Research Highlights in Nature Climate Change, August 2014.](https://www.nature.com/articles/nclimate2366)



----

<br> 

### Other Publications

<br>

#### [__Socio-economic Impact of Outer Continental Shelf Wind Energy Development on Fishing in the U.S. Atlantic.__](https://tethys.pnnl.gov/publications/socio-economic-impact-outer-continental-shelf-wind-energy-development-fisheries-us)

A. Justin Kirkpatrick, Sharon Benjamin, Geret DePiper, Tammy Murphy, Scott Steinback, and Chad Demarest. __OCS Study BOEM 2017-012. National Oceanic and Atmospheric Administration. National Marine Fisheries Service, Northeast Fisheries Science Center. (2017)__

Abstract: Commercial and recreational fisheries play a significant part in the U.S. economy and food supply. In 2011, U.S. landings by U.S. commercial fishermen totaled $5.3 billion in revenue and 4.5 million metric tons. Commercial harvesting alone employed over 186,000 individuals across the U. S. In 2011, 11 million recreational saltwater anglers caught an estimated 345 million fish during over 69 million trips nationwide. The nation’s fisheries operate alongside a variety of other ocean uses including transportation, natural resource extraction, and energy production. This report assesses the potential impacts to these fisheries and their shoreside dependents from wind energy development on the Atlantic Outer Continental Shelf (OCS).

This analysis was conducted by the National Oceanic and Atmospheric Administration (NOAA) National Marine Fisheries Service (NMFS) for the Bureau of Ocean Energy Management (BOEM). BOEM is responsible for managing activities associated with development of Wind Energy Areas (WEAs) on the OCS. Under the National Environmental Policy Act (NEPA) and other legislation, regulations, and executive orders, BOEM is required to assess the potential impacts of WEA development. BOEM will use this report to inform decision-making related to leases on the North and Mid-Atlantic OCS; help interested stakeholders understand how the report data were developed and what they say; identify areas that require refined data analysis; and conduct an environmental assessment under NEPA.

The area covered in this report extends from Massachusetts to North Carolina and includes eight wind energy planning areas, some of which were leased and some of which were still in earlier planning stages at the time of this analysis in 2013. All eight areas are generally referred to as WEAs in this report. Both exposure to WEA development and the potential associated impacts are assessed for individual WEAs and cumulatively across all eight WEAs. Exposure identifies the individuals and groups likely to be affected by WEA development, while impact analysis estimates the magnitude and direction (gain or loss) of the WEA’s impact on those potentially affected individuals and groups.

Download Vol. 1 & Vol. 2 [here.](https://tethys.pnnl.gov/publications/socio-economic-impact-outer-continental-shelf-wind-energy-development-fisheries-us)

<br>


#### [__IPBES 2019: The assessment report of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services on Global Assessment of Biodiversity and Ecosystem Services__](https://doi.org/10.5281/zenodo.3831673)

Contributing Author. Download [here.](https://doi.org/10.5281/zenodo.3831673)





## Working Papers
All papers are available in the most recent version below

<br>


#### [__Estimating Congestion Benefits of Batteries for Unobserved Networks: A Machine Learning Approach__](Papers/kirkpatrickEnergyStorageJan2025.pdf)

Kirkpatrick, A. Justin

Abstract: I estimate the grid impacts of 180MW of battery storage capacity operating in California during 2009-2016. I find that one megawatt of energy storage decreases evening peak prices by up to \$1.87/MWh at the pricing node where the storage is installed. Off-peak prices increase only slightly, implying a benefit to ratepayers of \$79,942 per year. I use a Double Pooled LASSO-based estimator to uncover the unobserved network structure and thereby estimate the price effects at other locations across the grid. Overall, I find early energy storage mandates in California are only partially justified by ratepayer benefits. These patterns likely hold in any grid setting with inelastic peak supply relative to off-peak supply.

*Currently in submission*

Download most recent version [here.](Papers/kirkpatrickEnergyStorageJan2025.pdf)

 
<br>



#### [__Valuing Solar Subsidies__](Papers/Valuing_Solar_Subsidies-GKB-20250713.pdf)

Ken Gillingham, A. Justin Kirkpatrick, and Bryan Bollinger 

Abstract: Individuals trade present for future consumption across a range of economic behaviors, and this tradeoff may differ across socioeconomic groups. To assess these tradeoffs, we estimate a dynamic model of residential solar adoption and system sizing using household-level data that offer plausibly exogenous variation in the future benefits from adopting relative to upfront costs. We find implicit discount rates of 15.3%, 13.9%, and 10.0% for low-, medium-, and high-wealth households. This heterogeneity remarkably persists after accounting for credit scores. Counterfactual simulations demonstrate opportunities to reduce the regressivity of solar adoption, increase policy cost-effectiveness, and improve welfare for low-wealth households.

Note: Author order is randomized using AEA Author Randomization Tool

*Currently in submission*

Available [here.](Papers/Valuing_Solar_Subsidies-GKB-20250713.pdf)

Presented at NBER Spring EEE 2023. Earlier [NBER working paper here.](https://www.nber.org/papers/w33368)

<br>




#### [__Averting Expenditures and Desirable Goods: Consumer Demand for Bottled Water in the Presence of Fracking__](/Papers/Averting_expenditures_and_desirable_goods.pdf)

A. Justin Kirkpatrick, T. Robert Fetter (last updated July 2020; resting)

Abstract: Environmental conditions such as new industrial activity or drinking water quality violations may affect perceived water quality and cause individuals to invest in averting or defensive expenditures. Some recent papers use household expenditures on bottled water to measure the welfare effect of changes in water quality, arguing that these averting expenditures are a lower bound on compensating variation. We offer a new perspective and argue that when consumers choose averting behaviors such as substituting bottled water for tap water, their willingness to pay incorporates other characteristics of the good. If consumers get positive utility from these characteristics, then expenditures on bottled water do not actually represent a lower bound on the compensating variation for a change in water quality. Rather, the observed expenditures should be adjusted downward to account for consumers’ increased utility due to other desirable characteristics. We develop a structural model of demand for bottled water and estimate it using fine-resolution supermarket scanner data, and compare the resulting estimates to averting expenditures from a reduced-form model. We use a horizontal discrete choice demand framework, drawing upon literature in empirical industrial organization and allowing for individual heterogeneity. Our structural results value the disamenity of fracking for groundwater-reliant homes at \$4.14 per household per quarter, while our reduced form results estimate \$3.24.

Download [here.](Papers/Averting_expenditures_and_desirable_goods.pdf)


<br>


## Work-in-progress

<br>


#### __The (Dis)amenity of Visible Solar Panels__

Bryan Bollinger, Ken Gillingham, and A. Justin Kirkpatrick

Working abstract: As a strategy to reduce air pollution, rooftop solar is subsidized through a variety of public policies. However, little is known about the non-pecuinary incentives for adopting residential rooftop solar. We build on prior research examining the peer effects of solar and ask two questions: Do households consider the visibility of their own potential solar panels when adopting, and what moderates that effect. We show three stylized facts: First, registered Democrats are more likely to install solar, but registered Republicans are more responsive to the private payoffs of adopting solar. Second, while both registered Republicans and registered Democrats draw, on average, negative utility from having a *visible* solar panel, the effect is stronger amongst registered Republicans. Third, we find some evidence that this effect becomes stronger amongst registered Republicans when the focal household is located in an area that is predominantly Republican. We draw theoretical motivation from the literature on private provision of public goods, and highlight "warm glow", "signalling" and "identity" as potential theoretical mechnisms.

Presented at __AERE 2023__. Slides [here.](HideSlide/AERE2023/OwnViz_Solar_AERE2023.html#1)

<br>


#### __Heterogeneous Effects of Informational Energy Audits and the Split Incentive for Renters and Owners__

Soren Anderson and A. Justin Kirkpatrick

Abstract: We examine the effects of pure-information energy audits (EAU's) amongst homeowners and renters. We measure the effect of an EAU on per-heating degree day and per-cooling degree day relationships before and after an audit, employing rich controls and fixed effects in a difference-in-differences-in-slope specification. We find a significant negative effect of EAU's overall, but renters have an attenuated effect of nearly 50\%. We theorize that this is the result of the principal-agent problem in energy efficiency. Finally, we leverage plausibly exogenous variation in EAU assignment owing to water bill audits that also performed energy efficiency audits and find similar main effects. Our results from this specification are underpowered for identifying renter heterogeneity in EAU effects.

Presented at __Heartland 2022__. Slides [here.](Papers/SplitAgent_v3.pdf)

<br>

#### __Energy Insecurity and Redlined America__
Solo-authored

Working abstract: Low-income households frequently face excessive energy bills, despite their income limitations, that initially seem counter-intuitive. Some of this insecurity is attributable to the housing stock, which is less energy efficient in minority neighborhoods, even conditional on current income (Reames, 2016 in Energy Policy). I link this phenomenon to historic housing discrimination policy known as “redlining” which, in the 1930’s, designated tracts of urban areas as “minority appropriate” and subsequently limited lending to minorities outside of those areas. I control for endogenous selection of “redlined” areas by leveraging variation in the original survey data to identify redlined areas that originally had characteristics identical to nearby non-redlined areas, forming a quasi-experiment. Conditional on minority presence and income in both 1932 and 2010, current “redlined” areas have lower-efficiency housing stock and lower mobility of residents – a “hysteresis” effect from historic discrimination.

Presented at __AERE 2021__. Slides [here.](Papers/AERE 2021.pdf)

<br>
 

#### __Environmental Impacts of Energy Storage__
Solo-authored

Working Abstract: The environmental and health externalities of electricity demand vary through space and time as cost-minimizing dispatch varies the “marginal responding plant,’’ the plant that increases output to meet an increase in electricity demanded at some hour, in some location on the grid. Over the US and a typical year, the variation may be as much as a factor of 10, but no policy mechanism exists to price this externality into electricity rates. Energy storage allows for temporal shifting of electricity supply, charging when demand is low (overnight) and discharging when demand is high. Thus, energy storage use has important but ambiguous ramifications for externalities from local pollutants (NOx, SO2, PM2.5) and global pollutants like CO2. California, in particular, has wrestled with the net CO2 effect of energy storage, with some estimates suggesting storage increases CO2 output by drawing on high-emission sources to charge, then displacing lower-emission resources to discharge. This paper uses a highly detailed model of the marginal responding plant with increased spatial and temporal resolution relative to prior work, paired with a model of storage operation that accounts for local congestion costs to derive the net externality effects of energy storage. Preliminary results suggest that storage decreases net CO2 emissions, suggesting storage is an important part of reducing electricity-sector CO2 emissions.

Presented at __AERE 2020__. Slides [here.](Papers/Kirkpatrick_StorageEmissions_AERE2020.pdf)

<br>

#### __Locational Market Power: The Effect of Battery Storage in California__
Solo-authored

Working Abstract: Locational market power occurs in spatial electricity markets when physical constraints on transmission and distribution lines preclude “cheap’’ electricity from flowing to areas of high demand. This results in less elastic supply during congested hours in congested locations. Electricity generators located in these congested areas may leverage this power by shading bids upwards, extracting rents from ratepayers. This paper examines generator behavior at electricity pricing locations (“nodes”) using the arrival of grid-scale energy storage as a quasi-experiment, finding that generators increase output during the hours of highest demand. This suggests that generators are exercising market power by withholding production during very high demand periods and that energy storage may alter the incentive structure, moving existing generators into a competitive equilibrium. A model of residual demand and generator bidding is introduced and applied in California’s wholesale market over the period 2009-2016.

<br>

#### __Out to Sea: The Environmental Dimensions of Offshore Wind__
Solo-authored

Working abstract: Debate over the environmental impact of offshore wind relative to terrestrial wind has often overlooked the externalities produced or avoided by variation in the timing of offshore versus terrestial wind generation. Wind is produced at zero marginal cost, and thus generation displaces dispatchable fossil fuel generation in many markets, and at many hours of the day. The environmental and health externalities of electricity demand vary through space and time as cost-minimizing dispatch varies the “marginal responding plant,’’ the plant that increases output to meet an increase in electricity demanded at some hour, in some location on the grid. Since the environmental and health externalities of the displaced generation determine much of the welfare benefits from wind generation, it is important to consider the timing of offshore versus terrestrial wind, rather than simply the total amount or market value generated. This paper uses a highly detailed model of the marginal responding plant with increased spatial and temporal resolution relative to prior work, paired with data on offshore and terrestrial wind generation to derive the change in environmental and health externalities associated with offshore siting decisions. Results will inform important decisions on offshore wind siting currently being made in the US Atlantic.

<br>


