---
---

<link rel="stylesheet" href="styles.css" type="text/css">


### Works-in-progress
All projects are placed in the context of my research agenda in my research statement.


#### Energy Insecurity and Redlined America
Solo-authored

Working abstract: Low-income households frequently face excessive energy bills, despite their income limitations, that initially seem counter-intuitive. Some of this insecurity is attributable to the housing stock, which is less energy efficient in minority neighborhoods, even conditional on current income (Reames, 2016 in Energy Policy). I link this phenomenon to historic housing discrimination policy known as “redlining” which, in the 1930’s, designated tracts of urban areas as “minority appropriate” and subsequently limited lending to minorities outside of those areas. I control for endogenous selection of “redlined” areas by leveraging variation in the original survey data to identify redlined areas that originally had characteristics identical to nearby non-redlined areas, forming a quasi-experiment. Conditional on minority presence and income in both 1932 and 2010, current “redlined” areas have lower-efficiency housing stock and lower mobility of residents – a “hysteresis” effect from historic discrimination.

 

Environmental Impacts of Energy Storage
Solo-authored

Working Abstract: The environmental and health externalities of electricity demand vary through space and time as cost-minimizing dispatch varies the “marginal responding plant,’’ the plant that increases output to meet an increase in electricity demanded at some hour, in some location on the grid. Over the US and a typical year, the variation may be as much as a factor of 10, but no policy mechanism exists to price this externality into electricity rates. Energy storage allows for temporal shifting of electricity supply, charging when demand is low (overnight) and discharging when demand is high. Thus, energy storage use has important but ambiguous ramifications for externalities from local pollutants (NOx, SO2, PM2.5) and global pollutants like CO2. California, in particular, has wrestled with the net CO2 effect of energy storage, with some estimates suggesting storage increases CO2 output by drawing on high-emission sources to charge, then displacing lower-emission resources to discharge. This paper uses a highly detailed model of the marginal responding plant with increased spatial and temporal resolution relative to prior work, paired with a model of storage operation that accounts for local congestion costs to derive the net externality effects of energy storage. Preliminary results suggest that storage decreases net CO2 emissions, suggesting storage is an important part of reducing electricity-sector CO2 emissions.

Locational Market Power: The Effect of Battery Storage in California
Solo-authored

Working Abstract: Locational market power occurs in spatial electricity markets when physical constraints on transmission and distribution lines preclude “cheap’’ electricity from flowing to areas of high demand. This results in less elastic supply during congested hours in congested locations. Electricity generators located in these congested areas may leverage this power by shading bids upwards, extracting rents from ratepayers. This paper examines generator behavior at electricity pricing locations (“nodes”) using the arrival of grid-scale energy storage as a quasi-experiment, finding that generators increase output during the hours of highest demand. This suggests that generators are exercising market power by withholding production during very high demand periods and that energy storage may alter the incentive structure, moving existing generators into a competitive equilibrium. A model of residual demand and generator bidding is introduced and applied in California’s wholesale market over the period 2009-2016.

 

Out to Sea: The Environmental Dimensions of Offshore Wind
Solo-authored

Working abstract: Debate over the environmental impact of offshore wind relative to terrestrial wind has often overlooked the externalities produced or avoided by variation in the timing of offshore versus terrestial wind generation. Wind is produced at zero marginal cost, and thus generation displaces dispatchable fossil fuel generation in many markets, and at many hours of the day. The environmental and health externalities of electricity demand vary through space and time as cost-minimizing dispatch varies the “marginal responding plant,’’ the plant that increases output to meet an increase in electricity demanded at some hour, in some location on the grid. Since the environmental and health externalities of the displaced generation determine much of the welfare benefits from wind generation, it is important to consider the timing of offshore versus terrestrial wind, rather than simply the total amount or market value generated. This paper uses a highly detailed model of the marginal responding plant with increased spatial and temporal resolution relative to prior work, paired with data on offshore and terrestrial wind generation to derive the change in environmental and health externalities associated with offshore siting decisions. Results will inform important decisions on offshore wind siting currently being made in the US Atlantic.

 

Peer Effects and Conspicuous Conservation in Rooftop Solar Adoptions
With Ken Gillingham, Bryan Bollinger, Steven Sexton

Working abstract: Efforts to reduce negative externalities from electricity generation have emphasized distributed clean energy for well over two decades, primarily in the form of subsidies to adopters. However, non-pecuniary incentives may play a significant role in driving household adoption of clean energy generation. Previous work has established that additional solar panel installations increase the probability of subsequent adoption within a zip code (Bollinger and Gillingham, 2012 in Marketing Science). This paper seeks to disentangle one of the mechanisms of diffusion of these peer effects by leveraging exogenous variation in the visibility of a solar panel. Furthermore, we also generate a LiDAR (satellite) based method for determining the visibility of an installed solar panel accounting for nearby road alignment and intervening vegetation. In our empirical application, we construct a household panel consisting of ~90% of all households in Connecticut and estimate a model of household adoption probabilities. Results will inform policymakers about the effects of non-pecuniary incentives for residential solar installations.

 

Valuing Solar Subsidies
With Ken Gillingham, Bryan Bollinger, Steven Sexton

Working abstract: Existing rooftop solar subsidy regimes have generated additional solar capacity and generation at relatively high cost partly due to take-up by infra-marginal adopters, i.e., free-riders who would have adopted solar in the absence of subsidies. We consider how households trade off upfront solar PV system costs and future savings on grid electricity by exploiting exogenous variation in upfront capacity rebates in California and discrete changes in future energy savings across administrative borders. We also incorporate a unique source of exogenous variation in household solar decisions by including data from Google Sunroof, which models the rooftops of over 50 million households across the U.S., providing household-level variation in expected payoffs from solar investment even within utility rate and state incentive boundaries. We evaluate the efficiency of upfront capacity incentives that include a federal investment tax credit and state and local rebates relative to NEM policies common to 43 U.S. states. NEM policies subsidize a future stream of electricity generated over the 20-25-year lifetimes of solar PV systems. The stream of subsidies may be highly discounted by impatient households who are observed to under-invest in energy-saving durables in a phenomenon termed the “Energy Paradox” that is believed to yield an “Energy Efficiency Gap.” If households exhibit discount rates higher than market rates, then policymakers interested in increasing solar electricity generation could redeploy public resources embodied in NEM policies in the form of upfront capacity rebates or expected generation rebates that effectively arbitrage household impatience.